basePath: ""

ingress:
  enabled: true
  hosts:
    - host: inspector.example.com
      paths:
        - path: ""
          pathType: Prefix
  tls:
    - secretName: inspector-tls
      hosts:
        - inspector.example.com

env:
  trustedDetailBaseUrl: https://inspector.example.com
