apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-inspector.fullname" . }}
  labels:
    {{- include "k8s-inspector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-inspector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-inspector.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "k8s-inspector.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "k8s-inspector.fullname" . }}
            - secretRef:
                name: {{ include "k8s-inspector.fullname" . }}
          readinessProbe:
            {{- $readinessProbe := deepCopy .Values.readinessProbe -}}
            {{- $_ := set $readinessProbe.httpGet "path" (include "k8s-inspector.systemStatusPath" .) -}}
            {{- toYaml $readinessProbe | nindent 12 }}
          livenessProbe:
            {{- $livenessProbe := deepCopy .Values.livenessProbe -}}
            {{- $_ := set $livenessProbe.httpGet "path" (include "k8s-inspector.systemStatusPath" .) -}}
            {{- toYaml $livenessProbe | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ default (include "k8s-inspector.fullname" .) .Values.persistence.existingClaim }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
