apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-inspector.fullname" . }}
  labels:
    {{- include "k8s-inspector.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.secretEnv.apiKey | quote }}
