from typing import Protocol


class InspectionProvider(Protocol):
    def list_namespaces(self) -> dict: ...

    def list_namespace_labels(self, namespace: str) -> dict: ...

    def get_overview(self) -> dict: ...

    def run_cluster_inspection(self) -> dict: ...

    def run_namespace_inspection(self, namespace: str, label_selector: str | None) -> dict: ...

    def run_pod_inspection(self, namespace: str, pod_name: str) -> dict: ...

    def collect_diagnosis_context(self, namespace: str, scope: str | None) -> dict: ...
