from typing import Protocol


class InspectionProvider(Protocol):
    def get_overview(self) -> dict: ...

    def run_cluster_inspection(self) -> dict: ...

    def run_namespace_inspection(self, namespace: str, label_selector: str | None) -> dict: ...

    def collect_diagnosis_context(self, namespace: str, scope: str | None) -> dict: ...
